gpt4all_model:
  gpt4all_model_name: ggml-gpt4all-j-v1.3-groovy.bin
  gpt4all_model_folder_path: /Users/paritosh/Documents/
  gpt4all_backend: llama
  gpt4all_allow_streaming: true
  gpt4all_allow_downloading: false
  gpt4all_temperature: 1
  gpt4all_top_p: 0.1
  gpt4all_top_k: 40
  gpt4all_n_batch: 20
  gpt4all_n_threads: 10
  gpt4all_n_predict: 1056
  gpt4all_max_tokens: 1024
  gpt4all_repeat_last_n: 64
  gpt4all_penalty: 1.18